### PR TITLE
Library upgraded to AmCharts Version 4.8.4 (January 25, 2020).

### PR DESCRIPTION
**Pull request by andreaht**
Added more languages, more themes, exposed new properties, added deps to export chart data as xlsx or pdf, added plugins javascritpts.

### CODE REVIEW

**Comment by kevzlou7979** [comment]
Ok will be reviewing this on weekends.

**Comment by kevzlou7979** [comment]
I think I need to finalize https://github.com/GwtMaterialDesign/gwt-material-amcharts4/pull/8 this PR before merging this. Is this PR merged based on the `release_2.1` to avoid conflicts in the future?

**Comment by andreaht** [comment]
I don't think you will have conflicts, because I've updates and added the javascripts, removed old ones. I've also added some properties in the java sources for accessing some of the new features if the library.

**Comment by kevzlou7979** [comment]
Thanks for the PR - we will be finalizing the demo showcase too for the new features.

**Pull request merged**
